- name: разрешаем http
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "80"
    jump: ACCEPT
  notify: iptables save

- name: разрешаем https
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "443"
    jump: ACCEPT
  notify: iptables save
