- name: ставим пакеты
  package: name={{ item }} 
  loop:
    - nginx

- name: создаём каталог для сертификатов
  file:
    dest: /etc/nginx/ssl/
    state: directory
    owner: nginx
    mode: 0640

- name: основной конфиг nginx
  template: 
    src: nginx.conf.j2 
    dest: /etc/nginx/nginx.conf
    owner: nginx
    mode: 0640
  notify: restart nginx

- name: апстрим для сайтов
  template: 
    src: 0upstreams.conf.j2 
    dest: /etc/nginx/conf.d/0upstreams.conf
    owner: nginx
    mode: 0640
  notify: restart nginx

- name: копируем конфиги сайтов
  template: 
    src: "{{ item }}.j2" 
    dest: "/etc/nginx/conf.d/{{ item }}.conf"
    owner: nginx
    mode: 0640
  notify: restart nginx
  loop:
    - tomcat

- name: настраиваем файрволл
  include: firewall.yml
