- name: ставим пакеты
  apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
  loop:
    - nginx

- name: создаём каталог для сертификатов
  file:
    dest: /etc/nginx/ssl/
    state: directory
    owner: www-data
    mode: 0640

- name: основной конфиг nginx
  template: 
    src: nginx.conf.j2 
    dest: /etc/nginx/nginx.conf
    owner: www-data
    mode: 0640
  notify: restart nginx

- name: удаляем конфиг nginx
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: restart nginx

- name: апстрим для сайтов
  template: 
    src: 0upstreams.conf.j2 
    dest: /etc/nginx/conf.d/0upstreams.conf
    owner: www-data
    mode: 0640
  notify: restart nginx

- name: копируем конфиги сайтов
  template: 
    src: "{{ item }}.j2" 
    dest: "/etc/nginx/sites-available/{{ item }}"
    owner: www-data
    mode: 0640
  notify: restart nginx
  loop:
    - tomcat

- name: подключаем сайты nginx
  file:
    src: /etc/nginx/sites-available/{{ item }}
    dest: /etc/nginx/sites-enabled/{{ item }}
    state: link
  notify: restart nginx
  loop:
    - tomcat

- name: настраиваем файрволл
  include: firewall.yml
