---

- name: "bootstrap"
  hosts: all
  roles:
    - bootstrap
    - firewall
  become: True


- name: "Веб сервер"
  hosts: nginx
  become: True
  roles: 
    - nginx
  vars:
    tomcat_servers: "{{ groups['tomcat'] }}"
    tomcat_port: 8080


- name: "Tomcat"
  hosts: tomcat
  become: True
  vars:
    tomcat_version: 9.0.45
    
    tomcat_permissions_production: True

    jenkins_tomcat_home: "/opt/tomcat/webapps/"

  roles: 
    - zaxos.tomcat-ansible-role
    - jenkins_war


- name: 'Master сервер backup'
  hosts: backuper_master
  become: True
  roles: 
    - backuper_master

- name: 'сервера с каких бекапить'
  hosts: backupers
  become: True
  roles: 
    - backuper

- name: "завершение"
  hosts: all
  become: True
  tasks:
    - name: сохраняем файрвол
      shell: /usr/libexec/iptables/iptables.init save

    - name: сохраняем файрвол
      shell: /usr/libexec/iptables/ip6tables.init save
