---

- name: "bootstrap"
  hosts: all
  roles:
    - bootstrap
    - firewall
  become: True


- name: "Веб сервер"
  hosts: nginx
  become: True
  roles: 
    - firewall
    - nginx
  vars:
    tomcat_servers: "{{ groups['tomcat'] }}"
    tomcat_port: 8080


- name: "Tomcat"
  hosts: tomcat
  become: True
  roles: 
    - firewall
    - jenkins_war


- name: 'Master сервер backup'
  hosts: backuper_master
  become: True
  roles: 
    - backuper_master

- name: 'сервера с каких бекапить'
  hosts: backupers
  become: True
  roles: 
    - backuper
