- name: ставим rsync
  package: name=rsync

- name: закидываем ssh ключ
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', 'keys/backuper.pub') }}"
#    key: "{{ backup_ssh_key_pub }}"
