#создаём юзера и ключ

- name: ставим rsync
  apt: pkg=rsync update_cache=yes cache_valid_time=3600

- name: Создаём ssh-ключ для бекапа
  user:
    name: root
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
  register: backup_ssh

- name: Копируем публичный ключ для backuper
  fetch:
    src: "{{ backup_ssh.ssh_key_file }}.pub"
    dest: keys/backuper.pub
    flat: yes

- name: закидываем файл для бекапа
  template: 
    src: "backup-other.j2" 
    dest: "/etc/cron.daily/backup-other"
    mode: 0755

#- name: прописываем хосты в .ssh/known_hosts
#  known_hosts:
#    name: "{{ item }}"
#    state: present
#    key: "{{ lookup('pipe', 'ssh-keyscan {{ hostvars[item].ansible_host }}') }}"
#    hash_host: false
#  loop: "{{ groups.backupers |flatten(levels=1) }}"

- name: отключаем проверку ssh
  blockinfile:
    path: ~/.ssh/config
    create: yes
    marker: "# {mark} disable for backuper"
    block: |
      Host {{ groups.backupers | join(' ') }}
        StrictHostKeyChecking no
